version: "3"

services:
  jupyer:
    build:
      context: ./
      dockerfile: Dockerifle.gpu
    volumes:
      - ./project:/work
      - ./kaggle.json:/root/.kaggle/kaggle.json
    ports:
      - "8888:8888"
      - "8000:8000"
      - "5000:5000"