version: "3.8"

services:
  jupyter:
    build:
      context: ./
      dockerfile: Dockerfile.gpu
    volumes:
      - ./project:/work
      - ./kaggle.json:/root/.kaggle/kaggle.json
    ports:
      - "8888:8888"
      - "8000:8000"
      - "5000:5000"